Neo4j Spatial Geoserver Plugin
==============================

[IMPORTANT]
Tested with: GeoServer 2.1.1

== Building ==

----
mvn clean package
----

== Deployment into Geoserver ==

* unzip the +target/xxxx-geoserver-plugin.zip+ into $GEOSERVER_HOME/webapps/geoserver/WEB-INF/lib

* restart geoserver

* configure a new workspace

* configure a new datasource neo4j in your workspace. Point the "The directory path of the Neo4j database:" parameter to the relative (form the GeoServer working dir) or aboslute path to a Neo4j Spatial database with layers (see https://github.com/neo4j/spatial[Neo4j Spatial])

* in Layers, do "Add new resource" and choose your Neo4j datastore to see the exisitng Neo4j Spatial layers and add them.

== Testing in GeoServer trunk ==

* check out the geoserver source

----
svn co https://svn.codehaus.org/geoserver/trunk geoserver-trunk
----

* build the source

----
cd geoserver-trunk
mvn clean install
----

* check that you can run the web app as of http://docs.geoserver.org/latest/en/developer/maven-guide/index.html#running-the-web-module-with-jetty[The GeoServer Maven build guide]

----
cd src/web/app
mvn jetty:run
----

* in $GEOSERVER_SOURCE/src/web/app/pom.xml (https://svn.codehaus.org/geoserver/trunk/src/web/app/pom.xml), add the following lines under the profiles section:

----
    <profile>
      <id>neo4j</id>
      <dependencies>
        <dependency>
          <groupId>org.geotools</groupId>
          <artifactId>gt-neo4j-spatial</artifactId>
          <version>0.7-SNAPSHOT</version>
        </dependency>
      </dependencies>
    </profile>
----

* start thw webapp again
----
cd $GEOSERVER_SRC/src/web/app
mvn jetty:run
----

* find Neo4j installed as a datasource under http://localhost:8080
